services:
  
  backend:
    build:
      context: ./Capstone_Backend
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: bjameson
      MYSQL_PASSWORD: AVNS_YLq0wVMQoQY8LnSYZc0
      MYSQL_PORT: 25060
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"